export const COMMON_WORDS = [
    "time", "year", "people", "way", "day", "man", "thing", "woman", "life", "child",
    "world", "school", "state", "family", "student", "group", "country", "problem", "hand", "part",
    "place", "case", "week", "company", "system", "program", "question", "work", "government", "number",
    "night", "point", "home", "water", "room", "mother", "area", "money", "story", "fact",
    "month", "lot", "right", "study", "book", "eye", "job", "word", "business", "issue",
    "side", "kind", "head", "house", "service", "friend", "father", "power", "hour", "game",
    "line", "end", "member", "law", "car", "city", "community", "name", "president", "team",
    "minute", "idea", "kid", "body", "information", "back", "parent", "face", "others", "level",
    "office", "door", "health", "person", "art", "war", "history", "party", "result", "change",
    "morning", "reason", "research", "girl", "guy", "moment", "air", "teacher", "force", "education",
    "foot", "boy", "age", "policy", "everything", "process", "music", "market", "sense", "nation",
    "plan", "college", "interest", "death", "experience", "effect", "use", "class", "control", "care",
    "field", "development", "role", "effort", "rate", "heart", "drug", "show", "leader", "light",
    "voice", "wife", "police", "mind", "price", "report", "decision", "son", "view", "relationship",
    "town", "road", "arm", "difference", "value", "building", "action", "model", "season", "society",
    "tax", "director", "position", "player", "record", "paper", "space", "ground", "form", "event",
    "official", "matter", "center", "couple", "site", "project", "activity", "star", "table", "need",
    "court", "american", "oil", "situation", "cost", "industry", "figure", "street", "image", "phone",
    "data", "picture", "practice", "piece", "land", "product", "doctor", "wall", "patient", "worker",
    "news", "test", "movie", "north", "love", "support", "technology", "step", "baby", "computer",
    "type", "attention", "film", "republican", "tree", "source", "red", "organization", "network", "period",
    "letter", "condition", "choice", "store", "rest", "fire", "south", "floor", "campaign", "engine",
    "thousand", "security", "food", "bank", "west", "sport", "board", "subject", "officer", "loss",
    "strategy", "bill", "energy", "pressure", "style", "feeling", "science", "theory", "response", "card",
    "song", "camera", "weapon", "performance", "democrat", "candidate", "top", "bed", "truth", "leg",
    "author", "blue", "deal", "animal", "memory", "box", "list", "goal", "simple", "glass"
];
