import { NextResponse } from 'next/server';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { GAME_CONFIG } from '@/lib/gameConfig';
import { createLogger } from '@/lib/logger';
import type { ActionContext, ActionPayload } from '../context';
import { readNumber, readString } from '../context';
import { generateAiHint } from './aiHint';

const log = createLogger('api/game/action').child('hint');

/** Level at which a hint is generated by the AI rather than derived locally. */
const AI_HINT_LEVEL = 3;

const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * Rate-limit reads need to see every player's usage, which RLS hides, so they
 * go through the service role. Falls back to the caller's client if no service
 * key is configured — the limits then under-count rather than the request
 * failing outright.
 */
function getUsageClient(fallback: SupabaseClient): SupabaseClient {
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
    if (!serviceKey) return fallback;
    return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, serviceKey);
}

/** Returns a 429 response when either the per-game or per-IP quota is spent. */
async function checkHintQuota(
    ctx: ActionContext,
    usage: SupabaseClient,
    ipHash: string,
): Promise<Response | null> {
    const { count: playerGameCount } = await usage
        .from('api_usage')
        .select('*', { count: 'exact', head: true })
        .eq('game_id', ctx.gameId)
        .eq('user_id', ctx.user.id)
        .eq('endpoint', 'gemini-hint');

    if ((playerGameCount || 0) >= GAME_CONFIG.AI_HINT_LIMIT_PER_GAME_PLAYER) {
        return NextResponse.json({ error: 'Player hint limit reached for this game.' }, { status: 429 });
    }

    const { count: ipDailyCount } = await usage
        .from('api_usage')
        .select('*', { count: 'exact', head: true })
        .eq('ip_hash', ipHash)
        .eq('endpoint', 'gemini-hint')
        .gte('created_at', new Date(Date.now() - DAY_MS).toISOString());

    if ((ipDailyCount || 0) >= GAME_CONFIG.AI_HINT_LIMIT_PER_IP_DAY) {
        return NextResponse.json({ error: 'Daily IP hint limit reached.' }, { status: 429 });
    }

    return null;
}

/**
 * Buys the next hint level for a message.
 *
 * Levels 1 and 2 only need the new cipher the client already computed. Level 3
 * additionally asks Gemini for a clue, behind per-game and per-IP quotas. If
 * generation fails the player still gets their level — with a crude
 * first-letter fallback — rather than losing the points they spent.
 */
export async function handleGetHint(
    ctx: ActionContext,
    payload: ActionPayload,
): Promise<Response | void> {
    log.debug('request', 'Processing hint request', { game_id: ctx.gameId, user_id: ctx.user.id });

    const targetId = readString(payload, 'targetId');
    const nextLevel = readNumber(payload, 'nextLevel');
    const newCipherText = readString(payload, 'newCipherText');

    if (!targetId || nextLevel === undefined) {
        return NextResponse.json({ error: 'Missing targetId or nextLevel' }, { status: 400 });
    }

    let aiHint: string | null = null;

    if (nextLevel === AI_HINT_LEVEL) {
        const ip = ctx.request.headers.get('x-forwarded-for') || 'unknown';
        const usage = getUsageClient(ctx.supabase);

        const quotaResponse = await checkHintQuota(ctx, usage, ip);
        if (quotaResponse) return quotaResponse;

        const { data: message } = await ctx.supabase
            .from('messages')
            .select('content')
            .eq('id', targetId)
            .single();

        if (!message?.content) {
            log.warn('generate', 'Message content missing, cannot build a hint', {
                game_id: ctx.gameId, target_id: targetId,
            });
        } else {
            aiHint = await generateAiHint({
                word: message.content,
                gameId: ctx.gameId,
                userId: ctx.user.id,
                ipHash: ip,
                adminSupabase: usage,
            });

            if (!aiHint) {
                aiHint = `It relates to "${message.content.substring(0, 1)}..." (AI unavailable)`;
            }
        }
    }

    const update: { hint_level: number; cipher_text?: string; ai_hint?: string } = {
        hint_level: nextLevel,
        cipher_text: newCipherText,
    };
    if (aiHint) update.ai_hint = aiHint;

    const { error } = await ctx.supabase.from('messages').update(update).eq('id', targetId);
    if (error) throw error;

    return NextResponse.json({ success: true, ai_hint: aiHint });
}
